version: "3.3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'R00tPa$$wort3n'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  redis:
    image: "redis:alpine"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8090}:${PORT_WEB_UI-8090}"
    environment:
      - SERVICES=s3,sqs